# Generated by Django 4.2.7 on 2024-02-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('pw', models.CharField(max_length=100)),
            ],
        ),
    ]
