# Generated by Django 4.2.7 on 2024-02-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pw',
            new_name='userPassword',
        ),
    ]
