# Generated by Django 4.2.7 on 2024-03-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='participant_puuid',
        ),
    ]
