# Generated by Django 4.2.7 on 2024-03-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_participant_totalpings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCompare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damagePerMinuteOppo', models.FloatField(default=0)),
                ('damagePerMinuteRank', models.IntegerField(default=0)),
                ('bountyGoldOppo', models.IntegerField(default=0)),
                ('bountyGoldRank', models.IntegerField(default=0)),
                ('dpgOppo', models.FloatField(default=0)),
                ('dpgRank', models.IntegerField(default=0)),
                ('dptOppo', models.FloatField(default=0)),
                ('dptRank', models.IntegerField(default=0)),
                ('turretPlatesTakenOppo', models.IntegerField(default=0)),
                ('turretPlatesTakenRank', models.IntegerField(default=0)),
                ('killsNearTurret', models.FloatField(default=0)),
                ('killsNearTurretOppo', models.FloatField(default=0)),
                ('killsNearTurretRank', models.IntegerField(default=0)),
                ('takesdownsFirstXMinutesOppo', models.IntegerField(default=0)),
                ('takesdownsFirstXMinutesRank', models.IntegerField(default=0)),
                ('laneMinionsFirst10MinutesOppo', models.IntegerField(default=0)),
                ('laneMinionsFirst10MinutesRank', models.IntegerField(default=0)),
                ('ddptOppo', models.FloatField(default=0)),
                ('ddptRank', models.IntegerField(default=0)),
                ('dgptOppo', models.FloatField(default=0)),
                ('dgptRank', models.IntegerField(default=0)),
                ('killAfterHiddenWithAllyOppo', models.IntegerField(default=0)),
                ('killAfterHiddenWithAllyRank', models.IntegerField(default=0)),
                ('outnumberedKillsOppo', models.IntegerField(default=0)),
                ('outnumberedKillsRank', models.IntegerField(default=0)),
                ('moreEnemyJungleThanOpponentOppo', models.FloatField(default=0)),
                ('moreEnemyJungleThanOpponentRank', models.IntegerField(default=0)),
                ('visionScorePerMinuteOppo', models.FloatField(default=0)),
                ('visionScorePerMinuteRank', models.IntegerField(default=0)),
                ('totalPingsOppo', models.IntegerField(default=0)),
                ('totalPingsRank', models.IntegerField(default=0)),
                ('myTeamPings', models.IntegerField(default=0)),
                ('myTeamPingsOppo', models.FloatField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
            ],
        ),
    ]
