# Generated by Django 4.2.7 on 2024-03-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_participant_teamposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='champExperience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='champLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='championId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='participantId',
            field=models.IntegerField(default=0),
        ),
    ]
