# Generated by Django 4.2.7 on 2024-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_takesdownsfirstxminutesrank_participantcompare_takedownsfirstxminutesoppo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='item1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='item2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='item3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='item4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='item5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='item6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='spell1Casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='spell2Casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='spell3Casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='spell4Casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='summoner1Casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='summoner1Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='summoner2Casts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='summoner2Id',
            field=models.IntegerField(default=0),
        ),
    ]
